#!/bin/bash
#SBATCH --job-name=CellRanger_count_E4_redo2_roslin-mito
#SBATCH --output=CellRanger_count_E4_redo2_roslin-mito.log.txt

#SBATCH --mail-user=mackenzie.gavery@noaa.gov
#SBATCH --mail-type=ALL

#SBATCH -c 20

#SBATCH -D /home/mgavery

module load bio/cellranger/3.1.0
 
cellranger count \
 --id=oyster_E4_redo2_roslin-mito \
 --fastqs=oyster_embryo_r2-redo/outs/fastq_path,oyster_embryo_r2-redo_2/outs/fastq_path \
 --sample=E4,E4 \
 --transcriptome=Cgigas_Roslin_mkref_genome-CRv3 \
 --localcores=20 \
 --localmem=200 \
 --chemistry=SC3Pv3 \

