#!/bin/bash
#SBATCH --job-name=CellRanger_count_Bla_roslin-mito-forcecell
#SBATCH --output=CellRanger_count_Bla_roslin-mito_forecell.log.txt

#SBATCH --mail-user=mackenzie.gavery@noaa.gov
#SBATCH --mail-type=ALL

#SBATCH -c 20

#SBATCH -D /home/mgavery

module load bio/cellranger/3.1.0
 
cellranger count \
 --id=oyster_r1and2_Bla_roslin-mito-forcecell \
 --fastqs=oyster_scRNA-Seq_NextSeqlanes/oyster_embryo/outs/fastq_path/,oyster_scRNA-Seq_NextSeqlanes/oyster_embryo_r2/outs/fastq_path \
 --sample=Bla,Bla_2 \
 --transcriptome=Cgigas_Roslin_mkref_genome-CRv3 \
 --localcores=20 \
 --localmem=200 \
 --chemistry=SC3Pv3 \


